-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 10:25:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BitAcademyDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BitAcademyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id17762295_bitacademydb` DEFAULT CHARACTER SET utf8 ;
USE `id17762295_bitacademydb` ;

-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17762295_bitacademydb`.`Account` (
  `First Name` INT NOT NULL,
  `Insertion` VARCHAR(255) NOT NULL,
  `Surname` VARCHAR(255) NOT NULL,
  `E-mail Address` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Surname`, `E-mail Address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS id17762295_bitacademydb.`Admin`(
  `First Name` INT NOT NULL,
  `Insertion` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `E-mail Address` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Account_Surname` VARCHAR(255) NOT NULL,
  `Account_E-mail Address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Surname`, `E-mail Address`),
  INDEX `fk_Admin_Account_idx` (`Account_Surname` ASC, `Account_E-mail Address` ASC),
  CONSTRAINT `fk_Admin_Account`
    FOREIGN KEY (`Account_Surname` , `Account_E-mail Address`)
    REFERENCES `id17762295_bitacademydb`.`Account` (`Surname` , `E-mail Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17762295_bitacademydb`.`Planning` (
  `Chapter` VARCHAR(255) NOT NULL,
  `Subject` VARCHAR(255) NULL,
  `Starting Time` TIME NULL,
  `Stopping Time` TIME NULL,
  PRIMARY KEY (`Chapter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17762295_bitacademydb`.`Subjects` (
  `Subject` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Subject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17762295_bitacademydb`.`Chapters` (
  `Chapter` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Chapter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Subjects_has_Chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17762295_bitacademydb`.`Subjects_has_Chapters` (
  `Subjects_Subject` VARCHAR(45) NOT NULL,
  `Chapters_Chapter` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Subjects_Subject`, `Chapters_Chapter`),
  INDEX `fk_Subjects_has_Chapters_Chapters1_idx` (`Chapters_Chapter` ASC),
  INDEX `fk_Subjects_has_Chapters_Subjects1_idx` (`Subjects_Subject` ASC),
  CONSTRAINT `fk_Subjects_has_Chapters_Subjects1`
    FOREIGN KEY (`Subjects_Subject`)
    REFERENCES `id17762295_bitacademydb`.`Subjects` (`Subject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_has_Chapters_Chapters1`
    FOREIGN KEY (`Chapters_Chapter`)
    REFERENCES `id17762295_bitacademydb`.`Chapters` (`Chapter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Planning_has_Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17762295_bitacademydb`.`Planning_has_Subjects` (
  `Planning_Chapter` VARCHAR(255) NOT NULL,
  `Subjects_Subject` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Planning_Chapter`, `Subjects_Subject`),
  INDEX `fk_Planning_has_Subjects_Subjects1_idx` (`Subjects_Subject` ASC),
  INDEX `fk_Planning_has_Subjects_Planning1_idx` (`Planning_Chapter` ASC),
  CONSTRAINT `fk_Planning_has_Subjects_Planning1`
    FOREIGN KEY (`Planning_Chapter`)
    REFERENCES `id17762295_bitacademydb`.`Planning` (`Chapter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planning_has_Subjects_Subjects1`
    FOREIGN KEY (`Subjects_Subject`)
    REFERENCES `id17762295_bitacademydb`.`Subjects` (`Subject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BitAcademyDB`.`Account_has_Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17762295_bitacademydb`.`Account_has_Planning` (
  `Account_Surname` VARCHAR(255) NOT NULL,
  `Account_E-mail Address` VARCHAR(255) NOT NULL,
  `Planning_Chapter` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Account_Surname`, `Account_E-mail Address`, `Planning_Chapter`),
  INDEX `fk_Account_has_Planning_Planning1_idx` (`Planning_Chapter` ASC),
  INDEX `fk_Account_has_Planning_Account1_idx` (`Account_Surname` ASC, `Account_E-mail Address` ASC),
  CONSTRAINT `fk_Account_has_Planning_Account1`
    FOREIGN KEY (`Account_Surname` , `Account_E-mail Address`)
    REFERENCES `id17762295_bitacademydb`.`Account` (`Surname` , `E-mail Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_has_Planning_Planning1`
    FOREIGN KEY (`Planning_Chapter`)
    REFERENCES `id17762295_bitacademydb`.`Planning` (`Chapter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
